# Generated by Django 3.1 on 2020-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='Duke University', max_length=255),
            preserve_default=False,
        ),
    ]
