# Generated by Django 3.1 on 2020-12-07 19:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0004_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='active',
        ),
        migrations.AddField(
            model_name='course',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(default='Sunday', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(default='4:44'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default='4:44'),
        ),
    ]
