# Generated by Django 3.1 on 2020-12-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0006_auto_20201207_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='day',
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(default='4:44'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default='4:44'),
        ),
    ]
