# Generated by Django 3.1 on 2020-12-07 19:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0008_course_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=27),
        ),
    ]
