# Generated by Django 3.1 on 2020-12-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0009_auto_20201207_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(to='course_manager.Course'),
        ),
    ]
